### ISSUE TITLE
relocation truncated to fit: R_X86_64_32S against symbol

### ISSUE THREAD

**Issue by ctroupin** [gher-ulg/DIVA#7]
When compiling with `ifort` I get messages like these:
```
/tmp/ifortnXvtPa.o: In function `jmbconstr_..1':
constr.f:(.text+0x12c2): relocation truncated to fit: R_X86_64_32S against symbol `jmbcon_' defined in COMMON section in /tmp/ifortnXvtPa.o
constr.f:(.text+0x1384): relocation truncated to fit: R_X86_64_32S against symbol `jmbcon_' defined in COMMON section in /tmp/ifortnXvtPa.o
...
```
so that `diva.a` is not compiled.

O.S.: Linux, Ubuntu 16.04.5 LTS (Xenial Xerus)
Compiler: ifort

**Comment by ctroupin** [comment]
Adding `-mcmodel medium` to the compilation flags seems to help, see for example
https://software.intel.com/en-us/forums/intel-fortran-compiler-for-linux-and-mac-os-x/topic/268374

**Comment by jmbeckers** [comment]
Le 2018-09-19 à 3:52 PM, Charles Troupin a écrit :
> |relocation truncated to fit|

Probleme 64-32 bit; à gerer avec des flags du compilateur ?

--
